const news = [
  {
    id: 'garcia-benn-vegas',
    title: 'Garcia vs. Benn Confirmed for Las Vegas',
    date: 'Sep 12',
    tag: 'Confirmed',
    excerpt: 'Ryan Garcia returns against Conor Benn at T-Mobile Arena with the WBC welterweight title on the line — the grudge match is officially signed.',
    image: '/boxing/fights/garcia-benn.webp',
    href: '/fights/garcia-vs-benn',
  },
  {
    id: 'canelo-mbilli-riyadh',
    title: 'Canelo vs. Mbilli Set for Riyadh Season',
    date: 'Oct 31',
    tag: 'Confirmed',
    excerpt: "Boxing's biggest star meets unbeaten WBC champion Christian Mbilli in the Kingdom Arena headliner to close Riyadh Season.",
    image: '/boxing/fights/canelo-mbilli.webp',
    href: '/fights/canelo-vs-mbilli',
  },
  {
    id: 'joshua-fury-msg',
    title: 'Joshua vs. Fury Pencilled for MSG',
    date: 'Nov 20',
    tag: 'Rumour',
    excerpt: 'The heavyweight blockbuster a decade in the making is pencilled for Madison Square Garden in November — contracts still to be signed.',
    image: '/boxing/hero/hero-lockerroom.webp',
    href: '/fights/joshua-vs-fury',
  },
  {
    id: 'hrgovic-itauma',
    title: 'Hrgovic Stops Itauma to Win the IBF Title',
    date: 'Aug 29',
    tag: 'Result',
    excerpt: 'Filip Hrgovic crowned himself IBF heavyweight champion with a ninth-round stoppage of the previously unbeaten Moses Itauma at the O2.',
    image: '/boxing/fights/santillan-russell.webp',
    href: '/fights/hrgovic-vs-itauma',
  },
  {
    id: 'inoue-nakatani',
    title: 'Inoue Dominates Nakatani at the Tokyo Dome',
    date: 'May 2',
    tag: 'Result',
    excerpt: 'Naoya Inoue rolled past Junto Nakatani over 12 one-sided rounds in front of a record Tokyo Dome crowd.',
    image: '/boxing/fights/utria-mercado.webp',
    href: '/fights/inoue-vs-nakatani',
  },
  {
    id: 'benavidez-zurdo',
    title: 'Benavidez Knocks Out Zurdo Ramirez',
    date: 'May 2',
    tag: 'Result',
    excerpt: "David Benavidez announced himself at light heavyweight, stopping Zurdo Ramirez in six to take pole position at 175.",
    image: '/boxing/fights/hl-full-event.webp',
    href: '/fights/benavidez-vs-zurdo',
  },
  {
    id: 'usyk-verhoeven',
    title: 'Usyk Reigns at the Pyramids',
    date: 'May 23',
    tag: 'Result',
    excerpt: 'Oleksandr Usyk stopped Noa Verhoeven in the eleventh round in Giza to retain his unified heavyweight crown.',
    image: '/boxing/fights/rolly-teofimo.webp',
    href: '/fights/usyk-vs-verhoeven',
  },
  {
    id: 'ennis-zayas',
    title: 'Boots Ennis Passes the Zayas Test',
    date: 'Jun 27',
    tag: 'Result',
    excerpt: 'Jaron Boots Ennis outworked Xander Zayas in Brooklyn, strengthening his claim as the top man at super welterweight.',
    image: '/boxing/fights/hernandez-veron.webp',
    href: '/fights/ennis-vs-zayas',
  },
  {
    id: 'lopez-romero',
    title: 'Teofimo Beats Rolly Romero in Vegas',
    date: 'Aug 22',
    tag: 'Result',
    excerpt: 'Teofimo Lopez outboxed Rolando Romero over twelve rounds in Las Vegas to keep hold of his welterweight status.',
    image: '/boxing/fights/rolly-teofimo.webp',
    href: '/fights/rolly-vs-teofimo',
  },
  {
    id: 'nick-ball-belfast',
    title: 'Nick Ball Returns in Belfast on Dec 19',
    date: 'Dec 19',
    tag: 'Announced',
    excerpt: "Liverpool's Nick Ball challenges for world honours at the SSE Arena Belfast in his biggest night yet.",
    image: '/boxing/fights/hl-fight.webp',
    href: '/fights/nick-ball',
  },
  {
    id: 'katie-taylor-pili',
    title: 'Katie Taylor vs. Pili Agreed for Istanbul',
    date: 'Sep 26',
    tag: 'Announced',
    excerpt: 'The undisputed super lightweight champion returns against Dr. Ewa Pili agree a clash in Istanbul.',
    image: '/boxing/hero/hero-schedule.webp',
    href: '/fighters/katie-taylor',
  },
  {
    id: 'crawford-sheeraz',
    title: 'Crawford vs. Sheeraz Brewing',
    date: 'In talks',
    tag: 'Rumour',
    excerpt: "Terence Crawford and Hamzah Sheeraz are in talks for a mega light heavyweight title showdown late in the year.",
    image: '/boxing/hero/spotlight-benn.webp',
    href: '/fighters/terence-crawford',
  },
];

module.exports = { news };