const rankings = [
  {
    id: 'p4p',
    name: 'Pound-for-Pound',
    source: 'Ring Magazine — Jun 2026',
    entries: [
      { rank: 1, name: 'Naoya Inoue', country: 'JP', record: '33-0-0 (27 KO)', note: 'Ring Super Bantamweight Champion' },
      { rank: 2, name: 'Oleksandr Usyk', country: 'UA', record: '24-0-0 (15 KO)', note: 'Unified Heavyweight' },
      { rank: 3, name: 'Shakur Stevenson', country: 'US', record: '24-0-0 (9 KO)', note: 'Ring Super Lightweight Champion' },
      { rank: 4, name: 'Jesse Rodriguez', country: 'US', record: '22-1-0 (13 KO)', note: 'Super Flyweight Champion' },
      { rank: 5, name: 'David Benavidez', country: 'US', record: '32-0-0 (26 KO)', note: 'Super Middleweight' },
      { rank: 6, name: 'Dmitry Bivol', country: 'KG', record: '25-1-0 (10 KO)', note: 'Ring Light Heavyweight Champion' },
      { rank: 7, name: 'Junto Nakatani', country: 'JP', record: '32-1-0 (24 KO)', note: 'Bantamweight' },
      { rank: 8, name: 'Devin Haney', country: 'US', record: '33-0-0 (14 KO)', note: 'WBO Welterweight Champion' },
      { rank: 9, name: 'Jaron Ennis', country: 'US', record: '35-0-0 (26 KO)', note: 'Ring Super Welterweight Champion' },
      { rank: 10, name: 'Oscar Collazo', country: 'US', record: '13-0-0 (9 KO)', note: 'Mini Flyweight Champion' },
    ],
  },
  {
    id: 'hw',
    name: 'Heavyweight',
    source: 'Ring Magazine — Jun 2026',
    champion: 'Agit Kabayel (WBC)',
    entries: [
      { rank: 1, name: 'Daniel Dubois', country: 'GB', record: '23-2-0 (19 KO)' },
      { rank: 2, name: 'Agit Kabayel', country: 'DE', record: '27-0-0 (17 KO)', note: 'WBC Champion' },
      { rank: 3, name: 'Tyson Fury', country: 'GB', record: '34-3-1 (24 KO)' },
      { rank: 4, name: 'Fabio Wardley', country: 'GB', record: '18-1-0 (17 KO)' },
      { rank: 5, name: 'Filip Hrgovic', country: 'HR', record: '18-1-0 (17 KO)', note: 'IBF Champion' },
      { rank: 6, name: 'Moses Itauma', country: 'GB', record: '12-0-0 (10 KO)' },
    ],
  },
  {
    id: 'smw',
    name: 'Super Middleweight',
    source: 'Ring / divisional — 2026',
    champion: 'Hamzah Sheeraz (WBO)',
    entries: [
      { rank: 1, name: 'David Benavidez', country: 'US', record: '32-0-0 (26 KO)' },
      { rank: 2, name: 'David Morrell', country: 'CU', record: '13-1-0 (10 KO)' },
      { rank: 3, name: 'Hamzah Sheeraz', country: 'GB', record: '24-0-1 (19 KO)', note: 'WBO Champion' },
    ],
  },
  {
    id: 'sw',
    name: 'Super Welterweight',
    source: 'Ring Magazine — Jul 2026',
    entries: [
      { rank: 1, name: 'Jaron Ennis', country: 'US', record: '35-0-0 (26 KO)' },
      { rank: 2, name: 'Vergil Ortiz', country: 'US', record: '23-0-0 (21 KO)' },
      { rank: 3, name: 'Sebastian Fundora', country: 'US', record: '21-1-1 (13 KO)' },
      { rank: 4, name: 'Israil Madrimov', country: 'UZ', record: '11-1-0 (8 KO)' },
      { rank: 5, name: 'Xander Zayas', country: 'PR', record: '22-0-0 (14 KO)' },
    ],
  },
  {
    id: 'w',
    name: 'Welterweight',
    source: 'Ring Magazine — May 2026',
    entries: [
      { rank: 1, name: 'Devin Haney', country: 'US', record: '33-0-0 (14 KO)', note: 'WBO Champion' },
      { rank: 2, name: 'Brian Norman Jr', country: 'US', record: '27-0-0 (25 KO)' },
      { rank: 3, name: 'Jack Catterall', country: 'GB', record: '33-2-0 (8 KO)' },
      { rank: 4, name: 'Ryan Garcia', country: 'US', record: '25-2-0 (20 KO)', note: 'WBC Champion' },
      { rank: 5, name: 'Liam Paro', country: 'AU', record: '28-1-0 (8 KO)', note: 'IBF Champion' },
      { rank: 6, name: 'Lewis Crocker', country: 'GB', record: '21-1-1 (13 KO)' },
    ],
  },
  {
    id: 'slw',
    name: 'Super Lightweight',
    source: 'Ring Magazine — Feb 2026',
    champion: 'Shakur Stevenson (Ring)',
    entries: [
      { rank: 1, name: 'Shakur Stevenson', country: 'US', record: '24-0-0 (9 KO)' },
      { rank: 2, name: 'Dalton Smith', country: 'GB', record: '18-0-0 (13 KO)' },
      { rank: 3, name: 'Richardson Hitchins', country: 'US', record: '21-0-0 (8 KO)' },
      { rank: 4, name: 'Keyshawn Davis', country: 'US', record: '15-0-0 (9 KO)' },
      { rank: 5, name: 'Teofimo Lopez', country: 'US', record: '22-1-0 (13 KO)' },
      { rank: 6, name: 'Alberto Puello', country: 'DO', record: '22-0-0 (18 KO)' },
    ],
  },
  {
    id: 'lw',
    name: 'Lightweight',
    source: 'Ring Magazine — Jul/Aug 2026',
    entries: [
      { rank: 1, name: 'Shakur Stevenson', country: 'US', record: '24-0-0 (9 KO)' },
      { rank: 2, name: 'Raymond Muratalla', country: 'US', record: '23-0-0 (18 KO)', note: 'IBF Champion' },
      { rank: 3, name: 'William Zepeda', country: 'MX', record: '34-1-0 (29 KO)' },
      { rank: 4, name: 'Abdullah Mason', country: 'US', record: '20-0-0 (17 KO)', note: 'WBO Champion' },
      { rank: 5, name: 'Andy Cruz', country: 'CU', record: '9-0-0 (2 KO)' },
      { rank: 6, name: 'Floyd Schofield', country: 'US', record: '20-0-0 (15 KO)' },
    ],
  },
  {
    id: 'sbw',
    name: 'Super Bantamweight',
    source: 'Ring Magazine — Jul 2026',
    champion: 'Naoya Inoue (Undisputed)',
    entries: [
      { rank: 1, name: 'Naoya Inoue', country: 'JP', record: '33-0-0 (27 KO)' },
      { rank: 2, name: 'Murodjon Akhmadaliev', country: 'UZ', record: '15-2-0 (11 KO)' },
      { rank: 3, name: 'Sam Goodman', country: 'AU', record: '22-1-0 (13 KO)' },
      { rank: 4, name: 'Junto Nakatani', country: 'JP', record: '32-1-0 (24 KO)' },
      { rank: 5, name: 'Alan Picasso Romero', country: 'MX', record: '18-0-0 (10 KO)' },
    ],
  },
];

module.exports = { rankings };