const videos = [
  {
    id: '9MiwQO-qhpc',
    title: 'Tyson Fury vs Deontay Wilder III | Full Fight Highlights',
    channel: 'PBC',
    category: 'classic',
    tag: 'Heavyweight',
    duration: '12:00',
  },
  {
    id: 'PzkltpFwAlw',
    title: 'Oleksandr Usyk vs Tyson Fury 2 Highlights | ESPN Ringside',
    channel: 'ESPN',
    category: 'classic',
    tag: 'Heavyweight',
    duration: '10:00',
  },
  {
    id: 'eacU_tjzyYM',
    title: 'Full Fight | Riyadh Season: Oleksandr Usyk vs Tyson Fury',
    channel: 'Ring Central',
    category: 'classic',
    tag: 'Heavyweight',
  },
  {
    id: 'MVxYTFkXa6A',
    title: 'Spence vs Crawford | Full Fight',
    channel: 'PBC',
    category: 'classic',
    tag: 'Welterweight',
  },
  {
    id: 'KihGo9jd2As',
    title: 'Ryan Garcia vs Rolando Romero | Fight Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Welterweight',
  },
  {
    id: '51TJpGenuck',
    title: 'Best Boxing Knockouts & Highlights 2024-2025 | Part 1',
    channel: 'Knockout Zone',
    category: 'highlights',
    tag: 'Knockouts',
  },
  {
    id: '7vDiRln38Uk',
    title: 'The Best Knockouts of 2025 (so far)',
    channel: 'Top Rank Boxing',
    category: 'highlights',
    tag: 'Knockouts',
  },
  {
    id: 'V-HF47QAgOs',
    title: 'Tyson Fury vs Arslanbek Makhmudov | Full Highlights',
    channel: 'Netflix Sports',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: 'Aja2KfuoqGA',
    title: 'Jake Paul vs Mike Tyson | Fight Highlights',
    channel: 'ESPN Ring',
    category: 'highlights',
    tag: 'Event',
  },
  {
    id: 'TJwSYPtnmV8',
    title: 'The Making of Canelo | Episode 1',
    channel: 'DAZN Boxing',
    category: 'doc',
    tag: 'Documentary',
  },
  {
    id: 'pU11EgyTK8A',
    title: '50-0: The Unbeatable Greatness of Floyd Mayweather Jr.',
    channel: 'Joseph Vincent',
    category: 'doc',
    tag: 'Documentary',
  },
  {
    id: 'R6dn5FhFBTc',
    title: 'Canelo vs Crawford: Jon Anik Breaks Down the Fight',
    channel: 'Netflix Sports',
    category: 'doc',
    tag: 'Preview',
  },
  {
    id: 'KFyNvUmJzmE',
    title: 'The Fire Inside | Official Trailer',
    channel: 'Amazon MGM Studios',
    category: 'doc',
    tag: 'Film',
  },
  {
    id: 'P-xDqzj6Vp0',
    title: 'Advanced Boxing Training Drills',
    channel: 'Tony Jeffries',
    category: 'training',
    tag: 'Technique',
  },
  {
    id: 'kg1LYIzxVPk',
    title: 'Boxing Defense: Blocking, Slipping, Ducking & Rolling',
    channel: 'Lorenzo',
    category: 'training',
    tag: 'Technique',
  },
  {
    id: 'bIkRT1gcfJ4',
    title: 'The Ultimate Boxing Footwork Tutorial',
    channel: 'Oracle Boxing',
    category: 'training',
    tag: 'Technique',
  },
  {
    id: 'qJyyk3XlGgA',
    title: 'Canelo vs Crawford | Official Teaser Trailer',
    channel: 'Netflix',
    category: 'promo',
    tag: 'Promo',
  },
  {
    id: 'dmIfWg3srRc',
    title: 'Canelo vs Crawford | Special Trailer',
    channel: 'Netflix',
    category: 'promo',
    tag: 'Promo',
  },
  {
    id: 'Q4_jH6vDUUA',
    title: 'Canelo vs Crawford: New York Press Conference',
    channel: 'Netflix',
    category: 'promo',
    tag: 'Presser',
  },
  {
    id: 'T0vDjBzwHdY',
    title: 'Rolly vs. Teofimo | Full Fight Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Lightweight',
  },
  {
    id: 'g-ZCi94vriI',
    title: 'Rolly vs. Teofimo | Extended Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Lightweight',
  },
  {
    id: 'rz3eUQxkfQo',
    title: 'Rolly vs. Teofimo | Round-by-Round Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Lightweight',
  },
  {
    id: '4b-Ray_H03U',
    title: 'Hrgovic vs. Itauma | Full Fight Highlights',
    channel: 'Boxing Highlights',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: '73WstyfAWHI',
    title: 'Hrgovic vs. Itauma | Extended Highlights',
    channel: 'Boxing Highlights',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: 'rS0ayLB-BkA',
    title: 'Hrgovic vs. Itauma | The Big Finish',
    channel: 'Boxing Highlights',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: 'XB79TUE4H4M',
    title: 'Oleksandr Usyk vs. Rico Verhoeven | Official Fight Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: 'viOZMsgZYKg',
    title: 'Usyk vs. Verhoeven | Official Full Card Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: 'SaYqv59-ACU',
    title: 'Usyk vs. Verhoeven | Official Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: 'V3XBgf2bVek',
    title: 'Usyk vs. Verhoeven | The Rounds That Matter',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Heavyweight',
  },
  {
    id: 'e0aJReDWcMY',
    title: 'Benavidez vs. Zurdo | Official Fight Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Middleweight',
  },
  {
    id: 'MB0OhkqlOeI',
    title: 'Benavidez vs. Zurdo | Extended Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Middleweight',
  },
  {
    id: 'IBx2mY8TK6U',
    title: 'Benavidez vs. Zurdo | The Finish',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Middleweight',
  },
  {
    id: 'wvYrvXEvnhc',
    title: 'Naoya Inoue vs. Junto Nakatani | Official Fight Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Bantamweight',
  },
  {
    id: 'zNXymaemhI4',
    title: 'Inoue vs. Nakatani | Extended Highlights',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Bantamweight',
  },
  {
    id: 'I4S2Tz1ISfY',
    title: 'Inoue vs. Nakatani | Tokyo Dome Recap',
    channel: 'DAZN Boxing',
    category: 'highlights',
    tag: 'Super Bantamweight',
  },
  {
    id: 'ZdGcx9fiw8U',
    title: 'Ennis vs. Zayas | Full Fight',
    channel: 'Boxing Highlights',
    category: 'highlights',
    tag: 'Super Welterweight',
  },
  {
    id: '2aam7BcojxE',
    title: 'Ennis vs. Zayas | Full Fight Highlights',
    channel: 'Boxing Highlights',
    category: 'highlights',
    tag: 'Super Welterweight',
  },
  {
    id: '4U1saQT64Jc',
    title: 'Ennis vs. Zayas | Fight Week Highlights',
    channel: 'Boxing Highlights',
    category: 'highlights',
    tag: 'Super Welterweight',
  },
  {
    id: '3P4QeH0e2ps',
    title: 'Fury vs. Joshua | First Face-Off & Press Conference',
    channel: 'Boxing Highlights',
    category: 'promo',
    tag: 'Presser',
  },
];

const CATEGORIES = ['all', 'classic', 'highlights', 'doc', 'training', 'promo'];

module.exports = { videos, CATEGORIES };